services:
  # Django Backend
  web:
    build:
      context: .  
      dockerfile: Dockerfile  
    command: >
      sh -c "
      python manage.py migrate &&
      daphne -b 0.0.0.0 -p 8000 movienight.asgi:application"
    volumes:
      - .:/app        
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  # PostgreSQL Database
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  # Celery Worker
  celery:
    build:
      context: .      
      dockerfile: Dockerfile
    command: >
      sh -c "
      celery -A movienight worker --loglevel=INFO"
    volumes:
      - .:/app     
    env_file:
      - ./.env
    depends_on:
      - web
      - redis

  # Celery Beat
  celery-beat:
    build:
      context: .      
      dockerfile: Dockerfile
    command: >
      sh -c "
      celery -A movienight beat --loglevel=INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    volumes:
      - .:/app       
    env_file:
      - ./.env
    depends_on:
      - web
      - redis

volumes:
  postgres_data: {}