version: '3.8'

services:
  # Django Backend
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev  # Development-specific Dockerfile
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app  
    env_file:
      - ./.env  
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  # Celery Worker
  celery:
    build:
      context: .
      dockerfile: Dockerfile.dev  # Use same development Dockerfile
    command: >
      sh -c "
      celery -A movienight worker --loglevel=INFO"
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - web
      - redis

  # Celery Beat
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.dev  # Use same development Dockerfile
    command: >
      sh -c "
      celery -A movienight beat --loglevel=INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - web
      - redis

  # PostgreSQL Database
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: dev_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: