# Generated by Django 4.2.16 on 2024-10-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='groupchat_name',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
