# Generated by Django 4.2.16 on 2024-10-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatgroup_groupchat_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='file',
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
