# Generated by Django 4.2.16 on 2024-10-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_groupmessage_file_groupmessage_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='file_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='file_type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
