# Generated by Django 4.2.16 on 2024-10-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movienight_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
