# .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches:
      - main  # Run tests on every push to the main branch
  pull_request:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      USE_SQLITE_FOR_TESTS: "True"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --maxfail=5 --disable-warnings